# Settings affecting the status panel rendering
status-panel:
   
   # Unit of speed to show
   # Supported units are: kmh (kilometres per hour), mph (miles per hour), mps (metres per second), bpt (blocks per tick)
   # Defaults to kilometres per hour, if the given value is invalid
   unit-of-speed: UNIT_OF_SPEED

# Settings affecting the catenary
catenary:
   
   # Height of catenary lines above the rails
   height: CATENARY_HEIGHT
   
   # Material that the catenary lines must be made of
   material: CATENARY_MATERIAL
   
   # Settings for the substations
   substation:
      
      # Material type of the bottom block
      bottom-block: CATENARY_SUBSTATION_BOTTOM
      
      # Material type of the top block
      # Must be a solid block type because a lever is to be placed on top!
      top-block: CATENARY_SUBSTATION_TOP
      
      # List of material types that the substation's catenary support may be made out of (usually different kinds of fences)
      support-blocks: CATENARY_SUBSTATION_SUPPORT

# Settings affecting the update checking feature
updates:
   
   # Check whether an update is available at every server start
   # Admins might get 'MCTS.update' permission to also trigger an update check and receive a notification if an update is available
   check: UPDATE_CHECK
   
   # Automatically download a new update after checking whether one is available
   download: UPDATE_DOWNLOAD